using CodeGenerator.Abstractions;
using CodeGenerator.Assembly.Abstractions;
using CodeGenerator.Assembly.Template.NetTiers.Entities.StaticFile;
using CodeGenerator.Assembly.Template.NetTiers.Model.DatabaseInfo.DatabaseModel;
using CodeGenerator.Infrastructure;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
namespace CodeGenerator.Assembly.Template.NetTiers.Entities
{
    public class EntityBaseCoreGeneratedTemp : ICodeTemplate<EntitiesFactory, DatabaseInfoModel>
    {

        private IdentifierNameSyntax GetNamespace(DatabaseInfoModel contextModel)
        {
            return IdentifierName($"{contextModel.RootNameSpace}.Entities");
        }
        public async Task<IEnumerable<ICodeFile>> Generate(ITemplateRenderer renderer, IContextModel contextModel)
        {
            string className = "EntityBaseCore";
            var model = contextModel as DatabaseInfoModel;
            List<ICodeFile> codeFiles = new List<ICodeFile>() { new CodeFile($"{className}.generated.cs", className, await GetCompilationUnit(model, className)) };
            return codeFiles;
        }
        private async Task<CompilationUnitSyntax> GetCompilationUnit(DatabaseInfoModel model, string className)
        {

            var tree = CSharpSyntaxTree.ParseText(StaticFileResource.EntityBaseCore_generated);
            var compilationUnitSyntax = (CompilationUnitSyntax)await tree.GetRootAsync();

            var commentText = SyntaxFactory.Comment(
                @$"/*
File generated by {model.CompanyName} templates [{model.CompanyURL}]
Important: Do not modify this file. Edit the file EntityBase.cs instead.
*/");
            compilationUnitSyntax = compilationUnitSyntax.WithLeadingTrivia(commentText, SyntaxFactory.CarriageReturnLineFeed);

            var oldNamespace = compilationUnitSyntax.Members
                .OfType<NamespaceDeclarationSyntax>()
                .FirstOrDefault();

            if (oldNamespace != null)
            {
                // ساخت Namespace جدید با اسم جدید و نگه داشتن اعضای قبلی
                var newNamespace = oldNamespace.WithName(GetNamespace(model));

                // جایگزین کردن در root
                var newRoot = compilationUnitSyntax.ReplaceNode(oldNamespace, newNamespace);

            }

            return compilationUnitSyntax;
        }

    }
}

