//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Assembly.Template.NetTiers.Entities.StaticFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticFileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticFileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGenerator.Assembly.Template.NetTiers.Entities.StaticFile.StaticFileResource", typeof(StaticFileResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table entity.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	public abstract partial class EntityBase : EntityBaseCore
        ///	{
        ///	
        ///	}
        ///}.
        /// </summary>
        internal static string EntityBase {
            get {
                return ResourceManager.GetString("EntityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#region Using Directives
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization;
        ///using System.ComponentModel.DataAnnotations;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table entity.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	public abstract partial class EntityBaseCore : IEntity, INotifyPropertyChanged, IDataErrorInfo, IDeserializationCallback, INotifyPropertyChangi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityBaseCore_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///using Microsoft.Practices.EnterpriseLibrary.Common;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.Configuration;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.BackingStoreImplementations;
        ///using Microsoft.Practices.EnterpriseLibrary.Common.Configuration;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.Cryptography.Configuration;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityCache {
            get {
                return ResourceManager.GetString("EntityCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///using System.Reflection;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Entity Factory provides methods to create entity types from type names as strings.
        ///    /// &lt;/summary&gt;
        ///    public partial class EntityFactory : EntityFactoryBase, IEntityFactory
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Initializes a new instance of the &lt;see cref=&quot;EntityFactory&quot;/&gt; class.
        ///        /// &lt;/summary&gt;
        ///        public EntityFactory()
        ///        {
        ///            base.CurrentEntit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFactory {
            get {
                return ResourceManager.GetString("EntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Reflection;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Provides the core entity factory behavior.  Will create a type based on a string
        ///    /// or a type and will try to auto discover which assembly this type lives in, even if it&apos;s
        ///    /// not a local referenced assembly.
        ///    /// &lt;/summary&gt;
        ///    public abstract class EntityFactoryBase : IEntityFactory
        ///    {
        ///        #region Events
        ///        /// &lt;summary&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFactoryBase {
            get {
                return ResourceManager.GetString("EntityFactoryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Reflection;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Hold a list of &lt;see cref=&quot;Expression&quot;/&gt; instance.
        ///	/// &lt;/summary&gt;
        ///	public sealed class Expressions : CollectionBase
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Initializes a new instance of the &lt;c&gt;Expressions&lt;/c&gt; class.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;holeFilterExpression&quot;&gt;the filter expression that will be parsed to create the collection.&lt;/param&gt;
        ///		public Expressions (string holeFilterExpressio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFilter {
            get {
                return ResourceManager.GetString("EntityFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Reflection;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization.Formatters.Binary;
        ///using System.ComponentModel;
        ///using System.Text.RegularExpressions;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// This classes contains utilities functions for the &lt;see cref=&quot;IEntity&quot;/&gt; instances and collections.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;remarks&gt;All methods [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityHelper {
            get {
                return ResourceManager.GetString("EntityHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table&apos;s unique identifier.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;remarks&gt;
        ///	/// This file is generated once and will never be overwritten.
        ///	/// &lt;/remarks&gt;
        ///	[Serializable]
        ///	[CLSCompliant(true)]
        ///	public abstract partial class EntityKeyBase : EntityKeyBaseCore
        ///	{
        ///
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string EntityKeyBase {
            get {
                return ResourceManager.GetString("EntityKeyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table&apos;s unique identifier.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	[CLSCompliant(true)]
        ///	public abstract partial class EntityKeyBaseCore : IEntityKey
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Reads values from the supplied IDictionary object into
        ///		/// properties of the current object.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;values&quot;&gt;An IDictionary instance that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityKeyBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityKeyBaseCore_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Provides a means to weak reference and already created and untouched locate entities.
        ///    /// &lt;/summary&gt;	
        ///    public class EntityLocator //: Microsoft.Practices.ObjectBuilder.Locator 
        ///    {
        ///        //UnityContainer _container = new UnityContainer();
        ///        WeakRefDictionary&lt;string, object&gt; _weakDictionary = new WeakRefDictionary&lt;string, object&gt;();
        ///
        ///        /// &lt;summary&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityLocator {
            get {
                return ResourceManager.GetString("EntityLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections;
        ///using System.Runtime.Serialization;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	
        ///	/// &lt;summary&gt;
        ///	/// Entity Manager provides the management of entity location and creation.
        ///	/// This is responsible for providing the health and validity of entities as a whole.
        ///	/// &lt;/summary&gt;
        ///    public static class EntityManager
        ///    {
        ///        #region Fields
        ///        private static object syncObject = new object();
        ///        private  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityManager {
            get {
                return ResourceManager.GetString("EntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provide a generic comparer for our entity objects.
        ///	/// &lt;/summary&gt;
        ///	public class EntityPropertyComparer : IComparer
        ///	{
        ///		private string PropertyName;
        ///
        ///		/// &lt;summary&gt;
        ///		/// Provides Comparison opreations.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;propertyName&quot;&gt;The property to compare&lt;/param&gt;
        ///		public EntityPropertyComparer( string propertyName)
        ///		{
        ///			PropertyName = propertyName;
        ///		}
        ///
        ///		/// &lt;summary&gt;
        ///		/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityPropertyComparer {
            get {
                return ResourceManager.GetString("EntityPropertyComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///using System.Reflection;
        ///using System.Text;
        ///using regEx = System.Text.RegularExpressions;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides common utility methods for interacting with objects.
        ///	/// &lt;/summary&gt;
        ///	public static class EntityUtil
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Creates a new instance of the specified type.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;type&quot;&gt;The runtime type to instantiate.&lt;/param&gt;
        ///		/// &lt;returns [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityUtil {
            get {
                return ResourceManager.GetString("EntityUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///
        ///using System.Reflection;
        ///using System.ComponentModel;
        ///using System.ComponentModel.Design.Serialization;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides a unified way of converting types of values to other types, as well as for accessing standard values and subproperties.
        ///	/// Used by the nettiers strongly typed collection, so they can be saved in ViewState.
        ///	/// &lt;/summary&gt;
        ///	public class GenericTypeConverter : TypeConverter
        ///	{
        ///		/// &lt;summary&gt;
        ///		///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTypeConverter {
            get {
                return ResourceManager.GetString("GenericTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// List of possible state for an entity.
        ///    /// &lt;/summary&gt;
        ///	public enum EntityState
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Entity is unchanged
        ///        /// &lt;/summary&gt;
        ///        Unchanged=0, 
        ///
        ///        /// &lt;summary&gt;
        ///        /// Entity is new
        ///        /// &lt;/summary&gt;
        ///        Added=1, 
        ///
        ///        /// &lt;summary&gt;
        ///        /// Entity has been modified
        ///        /// &lt;/summary&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntity {
            get {
                return ResourceManager.GetString("IEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///using Microsoft.Practices.EnterpriseLibrary.Caching;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    interface IEntityCacheItem
        ///    {
        ///        TimeSpan EntityCacheDuration{ get; set; }
        ///        CacheItemPriority EntityCacheItemPriority { get; set;  }
        ///        ICacheItemExpiration EntityCacheItemExpiration { get; set; }
        ///        ICacheItemRefreshAction EntityCacheItemRefreshAction { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string IEntityCacheItem {
            get {
                return ResourceManager.GetString("IEntityCacheItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Exposes a factory to create an entity based on a typeString and a default type.
        ///    /// &lt;/summary&gt;
        ///    public interface IEntityFactory
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Create an entity based on a string.  
        ///        /// It will autodiscover the type based on any information we can gather.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;typeString&quot;&gt;string of entity to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityFactory {
            get {
                return ResourceManager.GetString("IEntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines a common property which represents the
        ///	/// unique identifier for a business object.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;EntityKey&quot;&gt;The value type or
        ///	/// class to be used for the EntityId property.&lt;/typeparam&gt;
        ///	public interface IEntityId&lt;EntityKey&gt; : IEntity where EntityKey : IEntityKey, new()
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Gets or sets the value of the unique identifier
        ///		/// for the current business ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityId {
            get {
                return ResourceManager.GetString("IEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System.Collections;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines a method that allows setting of property values
        ///	/// based on the key/value pairs of an IDictionary object.
        ///	/// &lt;/summary&gt;
        ///	public interface IEntityKey
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Reads values from the supplied IDictionary object into
        ///		/// properties of the current object.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;values&quot;&gt;An IDictionary instance that contains the key/value
        ///		/// p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityKey {
            get {
                return ResourceManager.GetString("IEntityKey", resourceCulture);
            }
        }
    }
}
