//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Assembly.Template.NetTiers.Entities.StaticFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticFileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticFileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGenerator.Assembly.Template.NetTiers.Entities.StaticFile.StaticFileResource", typeof(StaticFileResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///   /// &lt;summary&gt;
        ///   /// Object representing a broken validation rule
        ///   /// &lt;/summary&gt;
        ///   [Serializable()]
        ///   public class BrokenRule
        ///   {
        ///      private string _ruleName;
        ///      private string _description;
        ///      private string _property;
        ///	  
        ///	  /// &lt;summary&gt;
        ///	  /// Default parameterless constructor used by Reflection for Soap Serialization
        ///	  /// &lt;/summary&gt;
        ///	  private BrokenRule()
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrokenRule {
            get {
                return ResourceManager.GetString("BrokenRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.ComponentModel;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///   /// &lt;summary&gt;
        ///   /// A List of broken rules.
        ///   /// &lt;/summary&gt;
        ///   [Serializable()]
        ///   public class BrokenRulesList : BindingList&lt;BrokenRule&gt;
        ///   {
        ///
        ///      /// &lt;summary&gt;
        ///      /// Returns the firstRule &lt;see cref=&quot;BrokenRule&quot; /&gt; object
        ///      /// corresponding to the specified property.
        ///      /// &lt;/summary&gt;
        ///      /// &lt;param name=&quot;property&quot;&gt;The name of the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrokenRulesList {
            get {
                return ResourceManager.GetString("BrokenRulesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Reflection;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Static class that contains common validation rules.  Each rule conforms to the &lt;see cref=&quot;ValidationRuleArgs&quot;/&gt; delegate.
        ///    /// &lt;/summary&gt;
        ///    public static class CommonRules
        ///    {
        ///        #region NotNull
        ///
        ///        /// &lt;summary&gt;
        ///        /// Rule that does not allow a property v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonRules {
            get {
                return ResourceManager.GetString("CommonRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///using Behsaz.Entities;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.IO.MemoryMappedFiles;
        ///using System.Linq;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///
        ///namespace Behsaz.Data
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Handle the custom Cache senarios.
        ///    /// &lt;/summary&gt;
        ///    public sealed class CustomCacheManager : IDisposable
        ///    {
        ///        #region Fields &amp; Properties
        ///
        ///        private static object syncRoot = new object();
        ///
        ///        private static SortedDicti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomCacheManager {
            get {
                return ResourceManager.GetString("CustomCacheManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table entity.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	public abstract partial class EntityBase : EntityBaseCore
        ///	{
        ///	
        ///	}
        ///}.
        /// </summary>
        internal static string EntityBase {
            get {
                return ResourceManager.GetString("EntityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#region Using Directives
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization;
        ///using System.ComponentModel.DataAnnotations;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table entity.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	public abstract partial class EntityBaseCore : IEntity, INotifyPropertyChanged, IDataErrorInfo, IDeserializationCallback, INotifyPropertyChangi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityBaseCore_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///using Microsoft.Practices.EnterpriseLibrary.Common;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.Configuration;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.BackingStoreImplementations;
        ///using Microsoft.Practices.EnterpriseLibrary.Common.Configuration;
        ///using Microsoft.Practices.EnterpriseLibrary.Caching.Cryptography.Configuration;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityCache {
            get {
                return ResourceManager.GetString("EntityCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///using System.Reflection;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Entity Factory provides methods to create entity types from type names as strings.
        ///    /// &lt;/summary&gt;
        ///    public partial class EntityFactory : EntityFactoryBase, IEntityFactory
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Initializes a new instance of the &lt;see cref=&quot;EntityFactory&quot;/&gt; class.
        ///        /// &lt;/summary&gt;
        ///        public EntityFactory()
        ///        {
        ///            base.CurrentEntit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFactory {
            get {
                return ResourceManager.GetString("EntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Reflection;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Provides the core entity factory behavior.  Will create a type based on a string
        ///    /// or a type and will try to auto discover which assembly this type lives in, even if it&apos;s
        ///    /// not a local referenced assembly.
        ///    /// &lt;/summary&gt;
        ///    public abstract class EntityFactoryBase : IEntityFactory
        ///    {
        ///        #region Events
        ///        /// &lt;summary&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFactoryBase {
            get {
                return ResourceManager.GetString("EntityFactoryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Reflection;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Hold a list of &lt;see cref=&quot;Expression&quot;/&gt; instance.
        ///	/// &lt;/summary&gt;
        ///	public sealed class Expressions : CollectionBase
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Initializes a new instance of the &lt;c&gt;Expressions&lt;/c&gt; class.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;holeFilterExpression&quot;&gt;the filter expression that will be parsed to create the collection.&lt;/param&gt;
        ///		public Expressions (string holeFilterExpressio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFilter {
            get {
                return ResourceManager.GetString("EntityFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Reflection;
        ///using System.Xml.Serialization;
        ///using System.Runtime.Serialization.Formatters.Binary;
        ///using System.ComponentModel;
        ///using System.Text.RegularExpressions;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// This classes contains utilities functions for the &lt;see cref=&quot;IEntity&quot;/&gt; instances and collections.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;remarks&gt;All methods [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityHelper {
            get {
                return ResourceManager.GetString("EntityHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table&apos;s unique identifier.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;remarks&gt;
        ///	/// This file is generated once and will never be overwritten.
        ///	/// &lt;/remarks&gt;
        ///	[Serializable]
        ///	[CLSCompliant(true)]
        ///	public abstract partial class EntityKeyBase : EntityKeyBaseCore
        ///	{
        ///
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string EntityKeyBase {
            get {
                return ResourceManager.GetString("EntityKeyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// The base object for each database table&apos;s unique identifier.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	[CLSCompliant(true)]
        ///	public abstract partial class EntityKeyBaseCore : IEntityKey
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Reads values from the supplied IDictionary object into
        ///		/// properties of the current object.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;values&quot;&gt;An IDictionary instance that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityKeyBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityKeyBaseCore_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Provides a means to weak reference and already created and untouched locate entities.
        ///    /// &lt;/summary&gt;	
        ///    public class EntityLocator //: Microsoft.Practices.ObjectBuilder.Locator 
        ///    {
        ///        //UnityContainer _container = new UnityContainer();
        ///        WeakRefDictionary&lt;string, object&gt; _weakDictionary = new WeakRefDictionary&lt;string, object&gt;();
        ///
        ///        /// &lt;summary&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityLocator {
            get {
                return ResourceManager.GetString("EntityLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections;
        ///using System.Runtime.Serialization;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	
        ///	/// &lt;summary&gt;
        ///	/// Entity Manager provides the management of entity location and creation.
        ///	/// This is responsible for providing the health and validity of entities as a whole.
        ///	/// &lt;/summary&gt;
        ///    public static class EntityManager
        ///    {
        ///        #region Fields
        ///        private static object syncObject = new object();
        ///        private  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityManager {
            get {
                return ResourceManager.GetString("EntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provide a generic comparer for our entity objects.
        ///	/// &lt;/summary&gt;
        ///	public class EntityPropertyComparer : IComparer
        ///	{
        ///		private string PropertyName;
        ///
        ///		/// &lt;summary&gt;
        ///		/// Provides Comparison opreations.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;propertyName&quot;&gt;The property to compare&lt;/param&gt;
        ///		public EntityPropertyComparer( string propertyName)
        ///		{
        ///			PropertyName = propertyName;
        ///		}
        ///
        ///		/// &lt;summary&gt;
        ///		/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityPropertyComparer {
            get {
                return ResourceManager.GetString("EntityPropertyComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using Behsaz.Entities;
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Serves as the base class for objects that provide data access functionality.
        ///	/// Provides a default implementation of the IEntityProvider&amp;lt;Entity, EntityKey&amp;gt; interface.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;Entity&quot;&gt;The class of the business object being accessed.&lt;/typeparam&gt;
        ///	/// &lt;typeparam name=&quot;EntityKey&quot;&gt;The class of the EntityId
        ///	/// property of the specified bus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityProviderBase {
            get {
                return ResourceManager.GetString("EntityProviderBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.Specialized;
        ///using System.Configuration.Provider;
        ///using System.Diagnostics;
        ///using System.Text;
        ///
        ///using Behsaz.Entities;
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///	
        ///	
        ///	/// &lt;summary&gt;
        ///	/// Serves as the base class for objects that provide data access functionality.
        ///	/// Provides a default implementation of the IEntityProvider&amp;lt;Entity, EntityKey&amp;gt; interface.
        ///	/// &lt;/su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityProviderBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityProviderBaseCore.generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///using System.Reflection;
        ///using System.Text;
        ///using regEx = System.Text.RegularExpressions;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides common utility methods for interacting with objects.
        ///	/// &lt;/summary&gt;
        ///	public static class EntityUtil
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Creates a new instance of the specified type.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;type&quot;&gt;The runtime type to instantiate.&lt;/param&gt;
        ///		/// &lt;returns [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityUtil {
            get {
                return ResourceManager.GetString("EntityUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Serves as the base class for objects that provide data access functionality.
        ///	/// Provides a default implementation of the IEntityViewProvider&amp;lt;Entity&amp;gt; interface.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;Entity&quot;&gt;The class of the business object being accessed.&lt;/typeparam&gt;
        ///	/// &lt;remarks&gt;
        ///	/// This file is generated once and will never be overwritten.
        ///	/// &lt;/remarks&gt;
        ///	[Serializable]
        ///	[CLSCompl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityViewProviderBase {
            get {
                return ResourceManager.GetString("EntityViewProviderBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using Behsaz.Entities;
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Serves as the base class for objects that provide data access functionality.
        ///	/// Provides a default implementation of the IEntityViewProvider&amp;lt;Entity&amp;gt; interface.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;Entity&quot;&gt;The class of the business object being accessed.&lt;/typeparam&gt;
        ///	[Serializable]
        ///	[CLSCompliant(true)]
        ///	public abstract partial class EntityViewProviderBaseCore&lt;Ent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityViewProviderBaseCore_generated {
            get {
                return ResourceManager.GetString("EntityViewProviderBaseCore.generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///#endregion
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides the base functionality required to parse search terms.
        ///	/// &lt;/summary&gt;
        ///	[CLSCompliant(true)]
        ///	public abstract class ExpressionParserBase
        ///	{
        ///		#region Constructors
        ///
        ///		/// &lt;summary&gt;
        ///		/// Initializes a new instance of the ExpressionParserBase class.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;propertyName&quot;&gt;&lt;/param&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpressionParserBase {
            get {
                return ResourceManager.GetString("ExpressionParserBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //NETTIERS - This is a copy of the source code for EntLib 5.  This fixes a bug for webapps.
        /////http://entlib.codeplex.com/workitem/26760?projectname=entlib
        ///
        /////===============================================================================
        ///// Microsoft patterns &amp; practices Enterprise Library
        ///// Core
        /////===============================================================================
        ///// Copyright © Microsoft Corporation.  All rights reserved.
        ///// THIS CODE AND INFORMATION IS PROVIDED &quot;AS IS&quot; WITHOUT WARRAN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileConfigurationSouce {
            get {
                return ResourceManager.GetString("FileConfigurationSouce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //NETTIERS - This is a copy of the source code for EntLib 5.  This fixes a bug for webapps.
        /////http://entlib.codeplex.com/workitem/26760?projectname=entlib
        ///
        /////===============================================================================
        ///// Microsoft patterns &amp; practices Enterprise Library
        ///// Core
        /////===============================================================================
        ///// Copyright © Microsoft Corporation.  All rights reserved.
        ///// THIS CODE AND INFORMATION IS PROVIDED &quot;AS IS&quot; WITHOUT WARRAN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileConfigurationSouceElement {
            get {
                return ResourceManager.GetString("FileConfigurationSouceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///
        ///using System.Reflection;
        ///using System.ComponentModel;
        ///using System.ComponentModel.Design.Serialization;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides a unified way of converting types of values to other types, as well as for accessing standard values and subproperties.
        ///	/// Used by the nettiers strongly typed collection, so they can be saved in ViewState.
        ///	/// &lt;/summary&gt;
        ///	public class GenericTypeConverter : TypeConverter
        ///	{
        ///		/// &lt;summary&gt;
        ///		///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTypeConverter {
            get {
                return ResourceManager.GetString("GenericTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///using System.Collections;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///    /// List of possible state for an entity.
        ///    /// &lt;/summary&gt;
        ///	public enum EntityState
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Entity is unchanged
        ///        /// &lt;/summary&gt;
        ///        Unchanged=0, 
        ///
        ///        /// &lt;summary&gt;
        ///        /// Entity is new
        ///        /// &lt;/summary&gt;
        ///        Added=1, 
        ///
        ///        /// &lt;summary&gt;
        ///        /// Entity has been modified
        ///        /// &lt;/summary&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntity {
            get {
                return ResourceManager.GetString("IEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///using Microsoft.Practices.EnterpriseLibrary.Caching;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    interface IEntityCacheItem
        ///    {
        ///        TimeSpan EntityCacheDuration{ get; set; }
        ///        CacheItemPriority EntityCacheItemPriority { get; set;  }
        ///        ICacheItemExpiration EntityCacheItemExpiration { get; set; }
        ///        ICacheItemRefreshAction EntityCacheItemRefreshAction { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string IEntityCacheItem {
            get {
                return ResourceManager.GetString("IEntityCacheItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Exposes a factory to create an entity based on a typeString and a default type.
        ///    /// &lt;/summary&gt;
        ///    public interface IEntityFactory
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Create an entity based on a string.  
        ///        /// It will autodiscover the type based on any information we can gather.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;typeString&quot;&gt;string of entity to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityFactory {
            get {
                return ResourceManager.GetString("IEntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines a common property which represents the
        ///	/// unique identifier for a business object.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;EntityKey&quot;&gt;The value type or
        ///	/// class to be used for the EntityId property.&lt;/typeparam&gt;
        ///	public interface IEntityId&lt;EntityKey&gt; : IEntity where EntityKey : IEntityKey, new()
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Gets or sets the value of the unique identifier
        ///		/// for the current business ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityId {
            get {
                return ResourceManager.GetString("IEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System.Collections;
        ///#endregion
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines a method that allows setting of property values
        ///	/// based on the key/value pairs of an IDictionary object.
        ///	/// &lt;/summary&gt;
        ///	public interface IEntityKey
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Reads values from the supplied IDictionary object into
        ///		/// properties of the current object.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;values&quot;&gt;An IDictionary instance that contains the key/value
        ///		/// p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityKey {
            get {
                return ResourceManager.GetString("IEntityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Text;
        ///using Behsaz.Entities;
        ///#endregion
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines the common data access methods that can be used by the
        ///	/// ProviderDataSource control to interact with the underlying data store.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;Entity&quot;&gt;The class of the business object being accessed.&lt;/typeparam&gt;
        ///	/// &lt;typeparam name=&quot;EntityKey&quot;&gt;The class of the EntityId
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityProvider {
            get {
                return ResourceManager.GetString("IEntityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using Behsaz.Entities;
        ///#endregion
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Defines the common data access methods that can be used by the
        ///	/// ReadOnlyDataSource control to interact with the underlying data store.
        ///	/// &lt;/summary&gt;
        ///	/// &lt;typeparam name=&quot;Entity&quot;&gt;The class of the business object being accessed.&lt;/typeparam&gt;
        ///	public interface IEntityViewProvider&lt;Entity&gt; where Entity : new()
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Gets a page of rows from the DataSource.
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEntityViewProvider {
            get {
                return ResourceManager.GetString("IEntityViewProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///
        ///using System;
        ///using System.Collections.Specialized;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Configuration.Provider;
        ///
        ///using Behsaz.Entities;
        ///
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{	
        ///	/// &lt;summary&gt;
        ///	/// Interface for NetTiersProvider
        ///	/// &lt;/summary&gt;
        ///	public interface INetTiersProvider
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Creates the transaction.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;returns&gt;&lt;/returns&gt;
        ///        T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INetTiersProvider {
            get {
                return ResourceManager.GetString("INetTiersProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System;
        ///using System.Data;
        ///using System.Data.Common;
        ///
        ///using System.Diagnostics;
        ///using Microsoft.Practices.EnterpriseLibrary.Data;
        ///using Microsoft.Practices.EnterpriseLibrary.Data.Sql;
        ///#endregion Using directives
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// TransactionManager interface
        ///	/// &lt;/summary&gt;
        ///    public interface ITransactionManager
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Begins the transaction.
        ///        /// &lt;/summary&gt;
        ///        void BeginTransaction() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ITransactionManager {
            get {
                return ResourceManager.GetString("ITransactionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///
        ///using System.Runtime.Serialization;
        ///using System.Xml.Serialization;
        ///
        ///namespace Behsaz.Entities
        ///{
        ///   /// &lt;summary&gt;
        ///   /// A abstract generic base class for the nettiers entities that are generated from tables and views. 
        ///   /// Supports filtering, databinding, searching and sorting.
        ///   /// &lt;/summary&gt;
        ///   [Serializable]
        ///   public abstract class ListBase&lt;T&gt; : BindingList&lt;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListBase {
            get {
                return ResourceManager.GetString("ListBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///
        ///using System;
        ///using System.Collections.Specialized;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Configuration.Provider;
        ///
        ///using Behsaz.Entities;
        ///
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{	
        ///	///&lt;summary&gt;
        ///	/// The base class to implements to create a .NetTiers provider.
        ///	///&lt;/summary&gt;
        ///	public abstract class NetTiersProvider : NetTiersProviderBase
        ///	{
        ///		
        ///		///&lt;summary&gt;
        ///		/// Current TbasModuleProviderBase instance.
        ///		///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetTiersProvider {
            get {
                return ResourceManager.GetString("NetTiersProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///
        ///using System;
        ///using System.Collections.Specialized;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Configuration.Provider;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///using Behsaz.Entities;
        ///
        ///#endregion
        ///
        ///namespace Behsaz.Data.Bases
        ///{	
        ///	///&lt;summary&gt;
        ///	/// The base class to implements to create a .NetTiers provider.
        ///	///&lt;/summary&gt;
        ///	public abstract class NetTiersProviderBase : System.Configuration.Provider.ProviderBase [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetTiersProviderBase {
            get {
                return ResourceManager.GetString("NetTiersProviderBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Configuration.Provider;
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Reprensents the strongly typed collection of NetTiersProvider.
        ///	/// &lt;/summary&gt;
        ///	public class NetTiersProviderCollection : ProviderCollection
        ///	{
        ///		/// &lt;summary&gt;
        ///	    /// Gets the &lt;see cref=&quot;T:NetTiersProvider&quot;/&gt; with the specified name.
        ///	    /// &lt;/summary&gt;
        ///	    /// &lt;value&gt;&lt;/value&gt;
        ///	    public new NetTiersProvider this[string name]
        ///	    {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetTiersProviderCollection {
            get {
                return ResourceManager.GetString("NetTiersProviderCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Configuration;
        ///
        ///namespace Behsaz.Data.Bases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// The class that hold the configuration section for the NetTiers Service.
        ///    /// &lt;/summary&gt;
        ///    public class NetTiersServiceSection : ConfigurationSection
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Gets the providers.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;value&gt;The providers.&lt;/value&gt;
        ///        [ConfigurationProperty(&quot;providers&quot;)]
        ///        public ProviderSettingsCollection Providers
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetTiersServiceSection {
            get {
                return ResourceManager.GetString("NetTiersServiceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Behsaz.Data.Bases
        ///{
        ///    public sealed class ResetCacheSpecification
        ///    {
        ///        public string SemaphoreName { get; set; }
        ///
        ///        public string MemoryMappedFileName { get; set; }
        ///
        ///        internal bool HasValue()
        ///        {
        ///            return !string.IsNullOrEmpty(SemaphoreName) &amp;&amp; !string.IsNullOrEmpty(MemoryMappedFileName);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ResetCacheSpecification {
            get {
                return ResourceManager.GetString("ResetCacheSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///using System.Text;
        ///#endregion
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Parses search text into an expression that can
        ///	/// be used in a SQL WHERE clause.
        ///	/// &lt;/summary&gt;
        ///	[CLSCompliant(true)]
        ///	public class SqlExpressionParser : ExpressionParserBase
        ///	{
        ///		#region Declarations
        ///
        ///		private StringBuilder sql;
        ///
        ///		#endregion Declarations
        ///
        ///		#region Constructors
        ///
        ///		/// &lt;summary&gt;
        ///		/// Initializes a new instance of the SqlExp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlExpressionParser {
            get {
                return ResourceManager.GetString("SqlExpressionParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Text;
        ///using Behsaz.Entities;
        ///#endregion
        ///
        ///namespace Behsaz.Data
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Represents a SQL filter builder expression enumeration.
        ///    /// &lt;/summary&gt;
        ///    [CLSCompliant(true)]
        ///    public enum StringBuilderExpression
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Append
        ///        /// &lt;/summary&gt;
        ///        Append = 1,
        ///        /// &lt;summary&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlStringBuilder {
            get {
                return ResourceManager.GetString("SqlStringBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Configuration;
        ///using System.Text;
        ///#endregion
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Provides utility methods for generating SQL expressions.
        ///	/// &lt;/summary&gt;
        ///	[CLSCompliant(true)]
        ///	public static class SqlUtil
        ///	{
        ///		#region Declarations
        ///
        ///		/// &lt;summary&gt;
        ///		/// SQL AND keyword.
        ///		/// &lt;/summary&gt;
        ///		public static readonly String AND  = &quot;AND&quot;;
        ///		/// &lt;summary&gt;
        ///		/// SQL OR keyword.
        ///		/// &lt;/summary&gt;
        ///		public static readonly String OR   =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlUtil {
            get {
                return ResourceManager.GetString("SqlUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///using System;
        ///using System.Collections.Generic;
        ///#endregion
        ///
        ////*
        /// * $author: QmQ
        /// * $source: http://www.codeproject.com/useritems/SimpleStringTokenizer.asp
        /// * $date:   10-June-2006
        /// */
        ///namespace Behsaz.Data
        ///{
        ///
        ///    #region [Summary and remarks]
        ///    /// &lt;summary&gt;
        ///    /// Implements a StringTokenizer class for splitting a string
        ///    /// into substrings using a set of delimiters.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// C# version of the java.util.StringTokenizer cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringTokenizer {
            get {
                return ResourceManager.GetString("StringTokenizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Behsaz.Data.Bases
        ///{
        ///    public sealed class TableCacheValidityDurationItem
        ///    {
        ///        public string TableName { get; set; }
        ///
        ///        public int ValidityDuration { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string TableCacheValidityDuration {
            get {
                return ResourceManager.GetString("TableCacheValidityDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///
        ///using System.Runtime.Serialization;
        ///using System.Xml.Serialization;
        ///
        ///
        ///namespace Behsaz.Entities
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Represents a strongly typed list of .netTiers table entity that can be accessed by index. 
        ///	/// Provides methods to search, sort, and manipulate lists.
        ///	/// &lt;/summary&gt;
        ///	[Serializable]
        ///	public class TList&lt;T&gt; : ListBase&lt;T&gt; where T : IEntity, new()
        ///   	{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TList {
            get {
                return ResourceManager.GetString("TList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using directives
        ///using System;
        ///using System.Data;
        ///using System.Data.Common;
        ///
        ///using System.Diagnostics;
        ///using Microsoft.Practices.EnterpriseLibrary.Data;
        ///using Microsoft.Practices.EnterpriseLibrary.Data.Sql;
        ///
        ///#endregion Using directives
        ///
        ///namespace Behsaz.Data
        ///{
        ///	/// &lt;summary&gt;
        ///	/// TransactionManager is utility class that decorates a &lt;see cref=&quot;IDbTransaction&quot;/&gt; instance.
        ///	/// &lt;/summary&gt;
        ///	public class TransactionManager : ITransactionManager, IDisposable
        ///	{
        ///		#region Fields
        ///		privat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionManager {
            get {
                return ResourceManager.GetString("TransactionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using Microsoft.Practices.EnterpriseLibrary.Data;
        /////PSB 2006-05-26: should we use EntLib ExceptionPolicy.HandleException?
        /////using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;
        ///using Behsaz.Entities;
        ///
        ///namespace Behsaz.Data
        ///{
        ///	#region Repository Enumerations
        ///	
        ///	#region Load/Save Enums
        ///
        ///	/// &lt;summary&gt;
        ///	/// DeepLoad options for deep loading entities
        ///	/// &lt;/summary&gt;
        ///	public enum DeepLoadType : int
        ///	{
        ///		// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Xml.Serialization;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///   /// &lt;summary&gt;
        ///   /// Object that provides additional information about an validation rule.
        ///   /// &lt;/summary&gt;
        ///   public class ValidationRuleArgs
        ///   {
        ///    	private string _propertyName;
        ///      	private string _description;
        ///		private object _tag;
        ///		private string _friendlyName;
        ///
        ///		/// &lt;summary&gt;
        ///		/// Gets or sets the tag.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;value&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidationRuleArgs {
            get {
                return ResourceManager.GetString("ValidationRuleArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///   /// &lt;summary&gt;
        ///   /// Delegate providing the signature of all methods that will process validation rules.
        ///   /// &lt;/summary&gt;
        ///   /// &lt;remarks&gt;
        ///   /// &lt;para&gt;
        ///   /// The method handler should set the Description attribute of the 
        ///   /// &lt;see cref=&quot;ValidationRuleArgs&quot;/&gt; parameter so that a meaningful
        ///   /// error is returned.
        ///   /// &lt;/para&gt;&lt;para&gt;
        ///   /// If the data is valid, the method must [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidationRuleHandler {
            get {
                return ResourceManager.GetString("ValidationRuleHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///   /// &lt;summary&gt;
        ///   /// Object representing a validation rule for an object
        ///   /// &lt;/summary&gt;
        ///   internal class ValidationRuleInfo
        ///   {
        ///      private object _target;
        ///      private ValidationRuleHandler _handler;
        ///      private string _ruleName = String.Empty;
        ///      private ValidationRuleArgs _args;
        ///
        ///      /// &lt;summary&gt;
        ///      /// Returns a text representation of the rule which is the &lt;se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidationRuleInfo {
            get {
                return ResourceManager.GetString("ValidationRuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Behsaz.Entities.Validation
        ///{
        ///
        ///   /// &lt;summary&gt;
        ///   /// Maintains the list of validation rules associated with an object
        ///   /// &lt;/summary&gt;
        ///   [Serializable()]
        ///   public class ValidationRules
        ///   {
        ///      /// &lt;summary&gt;
        ///      /// List of rules that have not passed validation
        ///      /// &lt;/summary&gt;
        ///      private BrokenRulesList _brokenRules;
        ///
        ///      /// &lt;summary&gt;
        ///      /// Object associated with this list of rules.
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidationRules {
            get {
                return ResourceManager.GetString("ValidationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///
        ///using System.ComponentModel;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///
        ///using System.Runtime.Serialization;
        ///using System.Xml.Serialization;
        ///
        ///
        ///namespace Behsaz.Entities
        ///{
        ///   /// &lt;summary&gt;
        ///   /// A generic collection for the nettiers entities that are generated from views. 
        ///   /// Supports filtering, databinding, searching and sorting.
        ///   /// &lt;/summary&gt;
        ///   [Serializable]
        ///   public class VList&lt;T&gt; : ListBase&lt;T&gt;
        ///   {
        ///
        ///		/// &lt;summary&gt;
        ///		/// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VList {
            get {
                return ResourceManager.GetString("VList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Nettiers : Copied this from the Unity 1.2 source code for backwards compatability.
        /////This class no longer exists in Unity 2.0 and Nettiers uses this class.
        /////Only had to change a couple lines that were referencing things outside of this 
        /////file from the EntLib distribution.
        /////===============================================================================
        ///// Microsoft patterns &amp; practices
        ///// Unity Application Block
        /////===============================================================================
        ///// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeakRefDictionary {
            get {
                return ResourceManager.GetString("WeakRefDictionary", resourceCulture);
            }
        }
    }
}
